apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: smtss
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  replicas:
    min: 2
    max: 6
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /internal/is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /internal/prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 200m
      memory: 768Mi
  azure:
    application:
      enabled: true
      tenant: nav.no
  accessPolicy:
    inbound:
      rules:
        - application: syfosmmottak
        - application: pale-2
        - application: syfosmpapirmottak
        - application: smregistrering-backend
        - application: padm2
          namespace: teamsykefravr
          cluster: prod-gcp
    outbound:
      rules:
        - application: smtss-redis
      external:
        - host: mpls03.adeo.no
          ports:
            - name: mq
              port: 1414
              protocol: TCP
  secureLogs:
    enabled: true
  envFrom:
    - secret: smtss-secrets
    - secret: smtss-keystore-pwd
    - secret: smtss-redis-password
  filesFrom:
    - mountPath: /var/run/keystore
      secret: smtss-keystore
  env:
    - name: MQ_HOST_NAME
      value: mpls03.adeo.no
    - name: MQ_PORT
      value: '1414'
    - name: MQ_GATEWAY_NAME
      value: MPLS03
    - name: MQ_CHANNEL_NAME
      value: P_SMTSS
    - name: MQ_TSS_SAMHANDLER_SERVICE_QUEUE
      value: QA.P415.AS10_SAMHANDLER_SERVICE
    - name: MQ_KEYSTORE_PATH
      value: /var/run/keystore/smtss-keystore.jks
