apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: smtss
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
  annotations:
    texas.nais.io/enabled: "true"
spec:
  image: {{ image }}
  replicas:
    min: 1
    max: 2
    scalingStrategy:
      cpu:
        thresholdPercentage: 90
  port: 8080
  liveness:
    path: /internal/is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /internal/prometheus
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
        - id: elastic
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 20m
      memory: 500Mi
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
  accessPolicy:
    inbound:
      rules:
        - application: syfosmmottak
        - application: pale-2
        - application: syfosmpapirmottak
        - application: syfosmarena
        - application: syk-dig-backend
        - application: padm2
          namespace: teamsykefravr
          cluster: dev-gcp
    outbound:
      external:
        - host: b27apvl221.preprod.local
          ports:
            - port: 1413
  secureLogs:
    enabled: true
  valkey:
    - instance: smtss
      access: readwrite
  envFrom:
    - secret: smtss-secrets
  env:
    - name: MQ_HOST_NAME
      value: b27apvl221.preprod.local
    - name: MQ_PORT
      value: '1413'
    - name: MQ_GATEWAY_NAME
      value: MQLS03
    - name: MQ_CHANNEL_NAME
      value: Q1_SMTSS
    - name: MQ_TSS_SAMHANDLER_SERVICE_QUEUE
      value: QA.Q1_415.AS10_SAMHANDLER_SERVICE
