apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: smtss
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
  annotations:
    texas.nais.io/enabled: "true"
spec:
  image: {{ image }}
  replicas:
    min: 2
    max: 6
    scalingStrategy:
      cpu:
        thresholdPercentage: 90
  port: 8080
  liveness:
    path: /internal/is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /internal/prometheus
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
        - id: elastic
  resources:
    limits:
      memory: 2Gi
    requests:
      cpu: 60m
      memory: 850Mi
  azure:
    application:
      enabled: true
      tenant: nav.no
  accessPolicy:
    inbound:
      rules:
        - application: syfosmmottak
        - application: pale-2
        - application: syfosmpapirmottak
        - application: syfosmarena
        - application: syk-dig-backend
        - application: padm2
          namespace: teamsykefravr
          cluster: prod-gcp
    outbound:
      rules:
        - application: logging
          namespace: nais-system
      external:
        - host: mpls03.adeo.no
          ports:
            - port: 1414
  valkey:
    - instance: smtss
      access: readwrite
  envFrom:
    - secret: smtss-secrets
  env:
    - name: MQ_HOST_NAME
      value: mpls03.adeo.no
    - name: MQ_PORT
      value: '1414'
    - name: MQ_GATEWAY_NAME
      value: MPLS03
    - name: MQ_CHANNEL_NAME
      value: P_SMTSS
    - name: MQ_TSS_SAMHANDLER_SERVICE_QUEUE
      value: QA.P415.AS10_SAMHANDLER_SERVICE
